### ISSUE TITLE
Unable to run 'safari-prod' successfully - Missing environment variable: API_URL

### ISSUE THREAD

**Issue by piejanssens** [twofas/2fas-browser-extension#9]
```
yarn run safari-prod
yarn run v1.22.19
$ yarn clean && yarn generate-locales && npx browserslist@latest --update-db && cross-env EXT_PLATFORM=Safari NODE_ENV=production node_modules/.bin/webpack --mode production --progress --config webpack/production.config.js
$ rimraf --glob ./public/*
$ node webpack/utils/generateLocales.js
Debugger listening on ws://127.0.0.1:59670/92fa8302-96a0-4bdb-9bf4-c58e40913165
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Waiting for the debugger to disconnect...
Latest version:     1.0.30001516
Installed version:  1.0.30001516
caniuse-lite is up to date
caniuse-lite has been successfully updated

No target browser changes
 Webpack PROD Build [Safari] 
Failed to load /Users/pieter/2fas-browser-extension/.env.
[webpack-cli] Error: Missing environment variable: API_URL
    at /Users/pieter/2fas-browser-extension/node_modules/dotenv-webpack/dist/index.js:92:17
    at Array.forEach (<anonymous>)
    at Dotenv.gatherVariables (/Users/pieter/2fas-browser-extension/node_modules/dotenv-webpack/dist/index.js:87:30)
    at Dotenv.apply (/Users/pieter/2fas-browser-extension/node_modules/dotenv-webpack/dist/index.js:65:28)
    at createCompiler (/Users/pieter/2fas-browser-extension/node_modules/webpack/lib/webpack.js:76:12)
    at /Users/pieter/2fas-browser-extension/node_modules/webpack/lib/webpack.js:44:48
    at Array.map (<anonymous>)
    at createMultiCompiler (/Users/pieter/2fas-browser-extension/node_modules/webpack/lib/webpack.js:44:33)
    at create (/Users/pieter/2fas-browser-extension/node_modules/webpack/lib/webpack.js:134:16)
    at webpack (/Users/pieter/2fas-browser-extension/node_modules/webpack/lib/webpack.js:151:47)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by GrzegorzZajac000** [comment]
Hey there,

Thanks for reporting the bug on GitHub! If you want, you can build your own server based on the [2fas-server](https://github.com/twofas/2fas-server) repository. And if you just need it for testing, you can connect to our API using the link `https://api2.2fas.com`. Let us know if you need any help. Your contribution is awesome!

Cheers,
Greg

**Comment by piejanssens** [comment]
Hi @piejanssens,

I'm able to run the extension now after setting up the `.env`.
Is there any way I can have 'better' source maps that correspond to the actual code?
I'm seeing `process.env.EXT_PLATFORM` in the sourcemaps, so it's impossible to step through.

**Comment by GrzegorzZajac000** [comment]
What do you mean by source maps?

`EXT_PLATFORM` is a variable defined in build scripts. Take a look at `package.json` file. It contains all scripts needed for extension development.
